### ISSUE TITLE
디자인 변경사항 및 QA 4차

### ISSUE THREAD

**Issue by HamBP** [Nexters/Boolti#171]
## 작업할 내용 (추가될 때마다 쌓아두는 중)
- 일단은 예매 내역 상세 상단에 노출되는 넘버링만 상운이 새롭게 주는 ‘주문 번호’로 갱신을 부탁합니다요
- 환불 다이얼로그 좌측 정렬 및 마진 변경
- 유효성 검사 helper message는 unfocused 되었을 때만 출력 (환불 flow)
- 홈 화면 dim 처리 및 뱃지 변경 사항

**Comment by mangbaam** [comment]
유효성 검사 다시 확인해줘! 

https://boolti.notion.site/Input-Error-92c2ef252ca34a2e968be07f542098aa

<img width="600" alt="image" src="https://github.com/Nexters/Boolti/assets/44221447/d461dd3d-ddf1-4fd7-816d-d71f21c023e6">

**Comment by HamBP** [comment]
이거 혹시 개인 노션인가?? 우리 팀 노션에서 찾아도 안 보이넹.
empty일때는 검증 안 하도록 이미 처리되어 있어서 focus 상태일 때만 에러 안 보이게 처리하면 될 것 같아

**Comment by mangbaam** [comment]
https://discord.com/channels/1194687691762180126/1201083621382029342/1211115998724362331

ios-android 통합채널 확인하면 돼!

focus 아웃 됐을 때 검증하는 로직은 빠졌어!

**Comment by mangbaam** [comment]
아니! 그건 이전 스펙인 것 같고 최종이라고 적혀있는 거 보면 될 거 같아
