### ISSUE TITLE
요 커밋을 확인해주세여! (수정됨)

### ISSUE THREAD

**Issue by HamBP** [Nexters/Boolti#185]
### 참고 링크
- https://github.com/Nexters/Boolti/pull/182/commits/8235ad484ef3a2b98bee57ccb2658263fc85e7e7
- data/repository/AuthRepositoryImpl.kt의 kakaoLogin 메서드
- merge 과정에서 구현체 반환 타입과 인터페이스 반환 타입이 달라졌는데, 확인 부탁드려요

**Comment by mangbaam** [comment]
제보 감사합니다
