### ISSUE TITLE
공연 상세 공유하기 버그 수정

### ISSUE THREAD

**Issue by HamBP** [Nexters/Boolti#334]
- 네트워크 요청 완료 전 공유하기 버튼 눌렀을 때 show id 가 0으로 들어가는 문제 수정
- 공연 상세만 수정하기보다 전체적으로 로딩 처리가 필요해 보임

**Comment by mangbaam** [comment]
예매 종료된 경우에 하단 예매 버튼 비활성화 돼야 하는데, API 응답 오기 전 순간적으로 활성화된 버튼이 노출되는 문제도 있어!
빠르게 눌러보니까 예매 페이지까지 넘어가더라고. 이 부분도 같이 대응되면 좋겠다
